Exclude `vite.config.ts` from typechecking
This fixes error TS6305 which happens because `vite.config.ts` is being
included as source code when it's only config for the build tool.